//GAMES REDUCERS
export const GET_GAMES = "GET_GAMES"; //used by saga
export const GET_GAMES_BY_GENRES = "GET_GAMES_BY_GENRES"; //used by saga 
export const SET_GAMES = "SET_GAMES";
export const SET_LOADING_GAMES = "SET_LOADING_GAMES";
export const UNSET_LOADING_GAMES = "UNSET_LOADING_GAMES";

//GAME DETAIL REDUCER
export const GET_GAME_DETAIL = "GET_GAME_DETAIL";
export const SET_GAME_DETAIL = "SET_GAME_DETAIL";
export const SET_LOADING_GAME_DETAIL = "SET_LOADING_GAME_DETAIL";
export const UNSET_LOADING_GAME_DETAIL = "UNSET_LOADING_GAME_DETAIL";
 
//GENRES REDUCERS
export const GET_GENRES = "GET_GENRES"; //used by saga
export const SET_GENRES = "SET_GENRES";
export const SET_LOADING_GENRES = "SET_LOADING_GENRES";
export const UNSET_LOADING_GENRES = "UNSET_LOADING_GENRES";   



